/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardGroupRouteImport } from './routes/_dashboard/group'
import { Route as DashboardRestaurantIdTabRouteImport } from './routes/_dashboard/$restaurantId/$tab'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupRoute = DashboardGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRestaurantIdTabRoute =
  DashboardRestaurantIdTabRouteImport.update({
    id: '/$restaurantId/$tab',
    path: '/$restaurantId/$tab',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/group': typeof DashboardGroupRoute
  '/': typeof DashboardIndexRoute
  '/$restaurantId/$tab': typeof DashboardRestaurantIdTabRoute
}
export interface FileRoutesByTo {
  '/group': typeof DashboardGroupRoute
  '/': typeof DashboardIndexRoute
  '/$restaurantId/$tab': typeof DashboardRestaurantIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/group': typeof DashboardGroupRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/$restaurantId/$tab': typeof DashboardRestaurantIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/group' | '/' | '/$restaurantId/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/group' | '/' | '/$restaurantId/$tab'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/group'
    | '/_dashboard/'
    | '/_dashboard/$restaurantId/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/group': {
      id: '/_dashboard/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof DashboardGroupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/$restaurantId/$tab': {
      id: '/_dashboard/$restaurantId/$tab'
      path: '/$restaurantId/$tab'
      fullPath: '/$restaurantId/$tab'
      preLoaderRoute: typeof DashboardRestaurantIdTabRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardGroupRoute: typeof DashboardGroupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRestaurantIdTabRoute: typeof DashboardRestaurantIdTabRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGroupRoute: DashboardGroupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRestaurantIdTabRoute: DashboardRestaurantIdTabRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
